version: '2'

services:
  mariadb:
    image: mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=cake
      - MARIADB_DATABASE=cake
  myapp:
    image: daktela/cake:dev
    ports:
      - '8000:8000'
    command: "create-and-up"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=cake
      - DB_DATABASE=cake
    volumes:
      - './app:/var/www/html/'
    depends_on:
      - mariadb